openapi: '3.0.2'
info:
  title: Test API
  version: '0.1'
servers:
  - url: http://localhost:8000/api/v1
    description: Local
  - url: http://dev.quality.com/api/v1
    description: Dev
  - url: http://prod.quality.com/api/v1
    description: Production
paths:
  /products: 
    get: 
      responses:
        '200':
          description: OK