openapi: '3.0.2'
info:
  title: Core API
  version: '0.2'
servers:
  - url: http://localhost:8000/api/v1
    description: Local
  - url: http://dev.quality.com/api/v1
    description: Dev
  - url: http://prod.quality.com/api/v1
    description: Production
paths:
  /products: 
    get: 
      responses:
        '200':
          description: OK

  /products/{product_id}:
    get: 
      tags:
        - Product
      summary: ดูสินค้า
      parameters:
        - in: path
          name: product_id 
          schema: 
            type: integer
          required: true
      responses:
        '200':
          description: Object of product
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string 
                    example: OK
                  message: 
                    type: string 
                    example: Edited successfully
                  data:
                    $ref: "#/components/schemas/ProductResponse"

        '400': 
          $ref: "#/components/responses/BadRequest"
        '401': 
          $ref: "#/components/responses/Unauthenticated"
        '403': 
          $ref: "#/components/responses/Unauthorized"
    patch: 
      tags:
        - Product
      parameters:
        - in: path
          name: product_id 
          schema: 
            type: integer
          required: true 
      summary: แก้ไขสินค้า
      requestBody:
        description: สินค้าใหม่ที่จะเพิ่มในคลัง
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/ProductRequest'
      responses:
        '200':
          description: No data
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string 
                    example: OK
                  message: 
                    type: string 
                    example: Edited success
        '400': 
          $ref: "#/components/responses/BadRequest"
        '401': 
          $ref: "#/components/responses/Unauthenticated"
        '403': 
          $ref: "#/components/responses/Unauthorized"
    delete: 
      tags:
        - Product
      summary: ลบสินค้า
      parameters:
        - in: path
          name: product_id 
          schema: 
            type: integer
          required: true 
      responses:
        '200':
          description: No content
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status: 
                    type: string 
                    example: OK
                  message: 
                    type: string 
                    example: Deleted successfully
        '400': 
          $ref: "#/components/responses/BadRequest"
        '401': 
          $ref: "#/components/responses/Unauthenticated"
        '403': 
          $ref: "#/components/responses/Unauthorized"
components:
  schemas:
    ProductRequest:
      type: object
      properties:
        name:
          type: string
          example: จาน
        quantity:
          type: integer
          example: 100
        cost:
          type: number
          example: 50.10
        group:
          type: string
          example: PLATE
    ProductResponse:
      type: object
      properties:
        id: 
          type: integer
          example: 1
        name:
          type: string
          example: จาน
        quantity:
          type: integer
          example: 100
        cost:
          type: number
          example: 50.10
        group:
          type: string
          example: PLATE

    ProductResponseList: 
      type: array
      items: 
        type: object
        properties:
          id: 
            type: integer
          name:
            type: string
          quantity:
            type: integer
          cost:
            type: number
          group:
            type: string
      example:
        - id: 1 
          name: จาน
          quantity: 20
          cost: 10.5
          group: PLATE
        - id: 2
          name: ชาม
          quantity: 50
          cost: 12.6
          group: BOWL
    ProductResponse_id: 
      type: array
      items: 
        type: object
        properties:
          id: 
            type: integer
          name:
            type: string
          quantity:
            type: integer
          cost:
            type: number
          group:
            type: string
      example:
        - id: 1 
          name: จาน
          quantity: 20
          cost: 10.5
          group: PLATE
  responses:
    BadRequest: 
      description: Bad request
      content:
        application/json:
          schema:
            type: object
            properties:
              status: 
                type: string 
                example: ERR01
              message: 
                type: string 
                example: Invalid phone number
    Unauthenticated: 
      description: Unauthenticated
      content:
        application/json:
          schema:
            type: object
            properties:
              status: 
                type: string 
                example: ERR02
              message: 
                type: string 
                example: Please log in 
    Unauthorized: 
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              status: 
                type: string 
                example: ERR04
              message: 
                type: string 
                example: This role can't access